[package]
name = "protocol"
version = "0.1.0"
authors = ["neetdai <974498346@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.6"
futures = "0.3.5"
thiserror = "1.0.20"