name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository  
      uses: actions/checkout@v2

    # 跑检查
    - name: Run clippy
      run: cargo clippy

  
